version: "3"
services:
    mysql-service:
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=Devops@123
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpressuser
            - MYSQL_PASSWORD=Wordpress@123
        container_name: wordpress_db_container2
        image: mysql:8.0.32

    wordpress-service:
        ports:
            - '8888:80'
        build: .
        container_name: wordpress_app_container2
        environment:
            - DB_NAME=wordpressdb
            - DB_USER=wordpressuser
            - DB_PASSWORD=Wordpress@123
            - DB_HOST=wordpress_db_container2
