apiVersion: v1
kind: Service
metadata:
  name: wp-demo-service
spec:
  type: NodePort
  selector:
    app: wp-demo
  ports:
    - name: "wp-port"
      port: 80
      targetPort: 80
      nodePort: 30080
