apiVersion: v1
kind: Pod
metadata:
  name: wp-demo
  labels:
    app: wp-demo
spec:
  containers:
  - name: wp-demo-container
    image: sambhavbhurtel/sample_wordpress:1.0.0
    ports:
    - containerPort: 80

    env:
    - name: DB_NAME
      value: "wordpressdb"
    - name: DB_USER
      value: "wordpressuser"
    - name: DB_PASSWORD
      value: "Wordpress@123"
    - name: DB_HOST
      value: "wp-db-service"
